/*
 * This source file was generated by the Gradle 'init' task
 */
package kukicosas;





public class App {
    

    public static void main(String[] args) {
    
//Sistem.out.println(*saludo 2*);
//Sistem.out.println(*saludo 3*);
//sistem.out.println(saludo 4*);

for (int i=1; i <=4;i++ ){
    Sistem.out.println(*saludo *+i);
    
}
